CREATE TABLE tasks (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  done BOOLEAN NOT NULL DEFAULT false
);
